// CTL-SARS-006: EMP201 CSV and summary report generator.
// SARS EMP201 field layout: docs/seed-data/sars-filing-formats/emp201-field-layout.json
// All decimal formatting uses InvariantCulture to prevent locale-specific separators.
// CSV separator is semicolon (;) per SARS eFiling specification.

using System.Globalization;
using System.Text;

namespace ZenoHR.Infrastructure.Services.Filing.Emp201;

/// <summary>
/// Generates SARS EMP201 monthly declaration CSV files and human-readable summary reports.
/// CTL-SARS-006: Employer files EMP201 by the 7th of each following month.
/// </summary>
public sealed class Emp201Generator : IEmp201Generator
{
    private static readonly CultureInfo Invariant = CultureInfo.InvariantCulture;

    /// <inheritdoc/>
    public string GenerateCsv(Emp201Data data)
    {
        ArgumentNullException.ThrowIfNull(data);

        // CTL-SARS-006: Invariant check — sum of employee PAYE must match declared total (within R0.01)
        var linePaye = data.EmployeeLines.Sum(l => l.PayeDeducted);
        if (Math.Abs(linePaye - data.TotalPayeDeducted) > 0.01m)
            throw new InvalidOperationException(
                $"EMP201 invariant violation: sum of employee PAYE lines ({linePaye:F2}) " +
                $"does not match declared total ({data.TotalPayeDeducted:F2}). " +
                "Correct the payroll run before generating a filing.");

        var sb = new StringBuilder();

        // ── Header record ─────────────────────────────────────────────────────
        sb.AppendLine("RECORD_TYPE;EMPLOYER_PAYE_REF;EMPLOYER_NAME;TAX_PERIOD;TOTAL_PAYE;TOTAL_UIF_EMP;TOTAL_UIF_EMPR;TOTAL_SDL;EMPLOYEE_COUNT;GROSS_TOTAL;DUE_DATE;GENERATED_AT");
        sb.AppendLine(string.Join(";",
            "H",
            data.EmployerPAYEReference,
            data.EmployerTradingName,
            data.TaxPeriod,
            data.TotalPayeDeducted.ToString("F2", Invariant),
            data.TotalUifEmployee.ToString("F2", Invariant),
            data.TotalUifEmployer.ToString("F2", Invariant),
            data.TotalSdl.ToString("F2", Invariant),
            data.EmployeeCount.ToString(Invariant),
            data.TotalGrossRemuneration.ToString("F2", Invariant),
            data.DueDate.ToString("yyyy-MM-dd", Invariant),
            data.GeneratedAt.ToString("yyyy-MM-ddTHH:mm:ssZ", Invariant)));

        // ── Detail records ────────────────────────────────────────────────────
        sb.AppendLine("RECORD_TYPE;EMPLOYEE_ID;EMPLOYEE_NAME;TAX_REF;ID_OR_PASSPORT;GROSS;PAYE;UIF_EMP;UIF_EMPR;SDL;PAYMENT_METHOD");
        foreach (var line in data.EmployeeLines)
        {
            sb.AppendLine(string.Join(";",
                "D",
                line.EmployeeId,
                line.EmployeeFullName,
                line.TaxReferenceNumber,
                line.IdOrPassportNumber,
                line.GrossRemuneration.ToString("F2", Invariant),
                line.PayeDeducted.ToString("F2", Invariant),
                line.UifEmployee.ToString("F2", Invariant),
                line.UifEmployer.ToString("F2", Invariant),
                line.SdlEmployer.ToString("F2", Invariant),
                line.PaymentMethod));
        }

        return sb.ToString();
    }

    /// <inheritdoc/>
    public string GenerateSummaryReport(Emp201Data data)
    {
        ArgumentNullException.ThrowIfNull(data);

        var totalPayable = data.TotalPayeDeducted + data.TotalUif + data.TotalSdl;

        return $"""
            ZenoHR — EMP201 Monthly Declaration
            =====================================
            Employer:        {data.EmployerTradingName}
            PAYE Reference:  {data.EmployerPAYEReference}
            Period:          {data.PeriodLabel} ({data.TaxPeriod})
            Due Date:        {data.DueDate.ToString("dd MMMM yyyy", Invariant)}

            PAYE Deducted:   R {data.TotalPayeDeducted.ToString("N2", Invariant)}
            UIF (Employee):  R {data.TotalUifEmployee.ToString("N2", Invariant)}
            UIF (Employer):  R {data.TotalUifEmployer.ToString("N2", Invariant)}
            UIF Total:       R {data.TotalUif.ToString("N2", Invariant)}
            SDL:             R {data.TotalSdl.ToString("N2", Invariant)}
                             ------------------
            Total Payable:   R {totalPayable.ToString("N2", Invariant)}

            Gross Payroll:   R {data.TotalGrossRemuneration.ToString("N2", Invariant)}
            Employees:       {data.EmployeeCount}

            Generated:       {data.GeneratedAt.ToString("yyyy-MM-dd HH:mm", Invariant)} UTC
            Generated by:    {data.GeneratedByUserId}
            Run ID:          {data.PayrollRunId}
            """;
    }

    /// <inheritdoc/>
    public DateOnly CalculateDueDate(int year, int month)
    {
        // CTL-SARS-006: Due on the 7th of the following month.
        // If the 7th is Saturday (6) or Sunday (0), advance to Monday.
        var followingMonth = month == 12 ? new DateOnly(year + 1, 1, 7) : new DateOnly(year, month + 1, 7);

        return followingMonth.DayOfWeek switch
        {
            DayOfWeek.Saturday => followingMonth.AddDays(2),
            DayOfWeek.Sunday   => followingMonth.AddDays(1),
            _                  => followingMonth,
        };
    }
}
